# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 08:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0003_delete_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
            ],
        ),
    ]
