# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 20:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUserModel',
            fields=[
            ],
        ),
    ]
